title: The Chouins
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.625
  brandStrength: 0
  lightness: 0.4139785
  brandColors:
    - '#f7f5fa'
    - '#151a04'
    - '#bfccdf'
    - '#003e6a'
    - '#04ae94'
  rhythmicContrast: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Thechouins
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5310636
layout_spectrum: 0.693
