typography_spectrum: 0.5310636
color:
  saturation: 0.625
  lightness: 0.1236559
  brandStrength: 0
  brandColors:
    - '#f7f5fa'
    - '#151a04'
    - '#bfccdf'
    - '#003e6a'
    - '#04ae94'
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.693
analytics:
  twitter: null
  google: null
  facebook: null
name: Thechouins
cta:
  bucket: null
  version: null
  domain: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: The Chouins
description: la familia
purpose: []
