favicon: null
cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.7455197
  brandStrength: 0
  lightness: 0.3225806
  brandColors:
    - '#f7f5fa'
    - '#151a04'
    - '#bfccdf'
    - '#003e6a'
    - '#04ae94'
  rhythmicContrast: 0.8253431
typography_spectrum: 0.5310636
layout_spectrum: 0.62841
analytics:
  twitter: null
  google: null
  facebook: null
name: Thechouins
